Repository digital-land/submit, pull requests merged in 2024-09, with the labels that each got.

#344 Pass User-Agent header in URL validation HEAD request
  src/controllers/submitUrlController.js
  test/unit/submitUrlController.test.js
Labels: bug

#409 handle GeoX, GeoY columns in input data.
  src/models/requestData.js
  src/models/responseDetails.js
  src/services/asyncRequestApi.js
  src/views/check/results/no-errors.html
  test/unit/responseDetails.test.js
Labels: enhancement

#458 Update Readme
  readme.md
Labels: documentation

#469 NOTICKET: fix wrong referenece to resource id
  src/controllers/OrganisationsController.js
  test/unit/organisationsController.test.js
Labels: bug

#468 Create landing page
  src/assets/scss/index.scss
  src/routes/manage.js
  src/routes/schemas.js
  src/views/landing.html
  src/views/start.html
  test/unit/landingPage.test.js
Labels: enhancement
